### PR TITLE
Multiple changes to add tray for MacOS. Changes in visual items

### PR DESCRIPTION
**Pull request by okgarces**
Restore __static variable

If tray exists but window is closed

Minor changes. Reset timer if window is closed

### CODE REVIEW

**Comment by okgarces** [comment]
This could be an approach for add system tray icon and logic. I change some UI please let me know what do you think about it.

Right now, it's working in my MacOS, I am going to make tests in Windows as well.

**Comment by Splode** [comment]
Hi @okgarces and thanks for your contribution.

I've tested this on macOS and it works nicely. However, there are some issues with Windows, as the default taskbar position is at the bottom of the screen. When the window is restored from the tray, it is positioned _below_ the taskbar, which makes sense for macOS, but positions the window offscreen.

Also, I'm not sure about the stylistic changes to the UI. I see that you've made the layout more efficient in terms of space, but I think some of the proportions between elements are lost.

I think there's a way to incorporate some of the fine work that you've done, but it will require a bit more looking into, especially with regards to Windows.

Thanks again!

**Comment by okgarces** [comment]
Hi @Splode. I will tackle the Windows issues and I will update the PR.
About the UI changes, I think is more efficient and the screen is not too wide. However, I can go back with styles or how can I improve those?

**Comment by Splode** [comment]
@okgarces let's go back to the original UI style for this particular PR. I'm still open to the UI changes, but can you please make a separate PR for the style updates?

**Comment by okgarces** [comment]
@Splode thanks! I am working on it.

**Pull request closed without merging**
