### PR TITLE
Added counter for total sessions

### PR DESCRIPTION
**Pull request by mihaiconstantin**
Hi Chris,

As I mentioned in my email, I'm a big fan of your application. 

I added a small counter to keep track of how many Pomodoro sessions are completed. Not sure if this is something you or other users might find useful, but I find it helpful to have a rough idea of how I did that day. I thought of sharing (see screenshot below).

total_sessions

Best,
Mihai

### CODE REVIEW

**Comment by mihaiconstantin** [comment]
I realized this introduces a bug. Closing #84 and will send another PR with a better implementation.

**Comment by Splode** [comment]
Thanks for the contribution, @mihaiconstantin.

Out of curiosity, what was the bug you encountered? I didn't see anything in the code that stood out.

**Comment by mihaiconstantin** [comment]
@Splode Thanks for asking!

I was updating the total rounds counter based on the `INCREMENT_ROUND` mutation. However, that mutation is only triggered 3 times per work session<sup>1</sup> because the fourth time a reset is performed instead. So, every work session the total rounds counter would lag cumulatively. I think this is made clear by the `console.log` statements you added when you emit the events in `Timer-controller.vue` within method `checkRound()` (see screenshot below).

Looking at the code more carefully, I think a logical approach would be to:
- initialize the total rounds counter at 0 and only display it if it's higher than 0
- create a standalone mutation and action for the total rounds counter
- dispatch this action every time after a short or long break

I will try to send another PR.
 
image

<sup>1</sup>By work session I mean 4 Pomodoros in a row.

**Comment by Splode** [comment]
Good catch and thank you for the explanation!

**Pull request closed without merging**
